# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

puts "Creating comic series..."
Comic.create(name: "The Variants", author: "Gail Simone", illustrator: "Phil Noto", company: "Marvel Comics", protagonist: "Jessica Jones", cover_illustration: https://comicbookroundup.com/img/covers/t/the-variants-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "What would it really be like to meet an alternate version of yourself, another you who had made different choices and lived a completely different life as a result? That's the question facing Jessica Jones, as what seemed like a routine investigation instead has her encountering other incarnations of herself from across the Multiverse. Can Jessica get along with herself? Will she want to kill her other selves? And will seeing the lives she could have led drive her into a self-destructive spiral? This is what happens when you meet...the Variants!")

Comic.create(name: "Immortal X-Men", author: "Kieron Gillen", illustrator: "Lucas Werneck", company: "Marvel Comics", protagonist: "X-Men", cover_illustration: https://comicbookroundup.com/img/covers/i/immortal-x-men-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "The Quiet Council rules the Krakoan age, for better... or worse. Now, shaken by INFERNO and X LIVES / X DEATHS OF WOLVERINE they strive to hold together, no matter how much they want to tear each other apart. Writer Kieron Gillen (UNCANNY X-MEN, ETERNALS, The Wicked + The Divine, Die) returns to the world of X with artist Lucas Werneck (TRIAL OF MAGNETO) to bring us all into the room where it happens. It being the most powerful people on Earth deciding the fate of the whole planet. Prepare for sinister secrets to be revealed and learn that some secrets are more sinister than others...")

Comic.create(name: "The Amazing Spider-Man", author: "Zeb Wells", illustrator: "Ed McGuinness/David Lopez", company: "Marvel Comics", protagonist: "Spider-Man", cover_illustration: https://comicbookroundup.com/img/covers/a/amazing-spider-man-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "Peter's on the outs with the FF. He's on the outs with the Avengers. He's on the outs with Aunt May! No one wants to see Spider-Man - except for Doctor Octopus. Ock's on Spider-Man's tail and the Master Planner has something truly terrible planned for when he gets his tentacles on Spidey. All that, and what does Tombstone have planned? Just in time for Spider-Man's 60th Anniversary, a new volume of AMAZING SPIDER-MAN begins, and 2022 is going to be the biggest year for Spider-Man EVER!")

Comic.create(name: "Ant-Man", author: "Al Ewing", illustrator: "Tom Reilly", company: "Marvel Comics", protagonist: "Ant-Man", cover_illustration: https://comicbookroundup.com/img/covers/a/ant-man-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "Flash back to the early days of Hank Pym's career as the astonishing Ant-Man! It's date night for Hank and his girlfriend Janet Van Dyne, but nobody told that to Ant-Man's enemies! Watch as Hank's ant-agonists band together to finally take down the scientific adventurer! But will anyone come to his rescue? And who is the mysterious stranger who stalks him? Join Al Ewing (IMMORTAL HULK) and Tom Reilly (THE THING) as they explore the history of every hero (past, present and future!) called Ant-Man!")

Comic.create(name: "Daredevil", author: "Chip Zdarsky", illustrator: "Marco Checchetto", company: "Marvel Comics", protagonist: "Daredevil", cover_illustration: https://comicbookroundup.com/img/covers/d/daredevil-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "In the wake of Wilson Fisk's violent and visceral last act, it's a new era for New York and the Man Without Fear! With a groundbreaking creative team returning to usher in an all-new chapter, Matt Murdock has no choice but to leave behind everything he's ever known, and ELEKTRA is the last vestige of his former life. Everything Matt Murdock thought it meant to be DAREDEVIL is about to change, including the challenges he will have to face in the cowl!")

Comic.create(name: "Moon Knight", author: "Jed MacKay", illustrator: "Alessandro Cappuccio", company: "Marvel Comics", protagonist: "Moon Knight", cover_illustration: https://comicbookroundup.com/img/covers/m/moon-knight-(2021)/1_medium.jpg, release_year: 2021, ongoing: true, synopsis: "The mysterious Mr. Knight has opened his Midnight Mission, his people petitioning for protection from the weird and horrible. The Moon Knight stalks the rooftops and alleys marked with his crescent moon tag, bringing violence to any who would harm his people. Marc Spector, in whichever guise he dons, is back on the streets, a renegade priest of an unworthy god. But while Khonshu languishes in a prison that Moon Knight put him in, Moon Knight must still observe his duty: protecting those who travel at night.
Let it be known - Moon Knight will keep the faith.")

Comic.create(name: "Shang Chi and The Ten Rings", author: "Gene Luen Yang", illustrator: "Marcus To", company: "Marvel Comics", protagonist: "Shang Chi", cover_illustration: https://comicbookroundup.com/img/covers/s/shang-chi-and-the-ten-rings-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "Shang-Chi has gained possession of the powerful Ten Rings. But so much concentrated energy has not gone unnoticed. Now, every bounty hunter, assassin and evil syndicate in the Marvel Universe is coming to take the Rings from him! But will the responsibility and the truth of the Rings be too much to bear for the Master of Kung Fu? Find out as the true origin of the Ten Rings starts here from Gene Luen Yang (SHANG-CHI) and Marcus To (EXCALIBUR)!")

Comic.create(name: "Carnage", author: "Ram V", illustrator: "Francesco Manna", company: "Marvel Comics", protagonist: "Carnage", cover_illustration: https://comicbookroundup.com/img/covers/c/carnage-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "FOR YEARS, the only host the dangerous CARNAGE symbiote knew was CLETUS KASADY. Sharing a bond unique even among symbiotes and their hosts, the two were the most notorious and prolific serial killers in the Marvel Universe. But after the events of EXTREME CARNAGE, Cletus' codex has found a new home, leaving the Carnage symbiote adrift, alone... and deadlier than ever before!")

Comic.create(name: "Star Wars", author: "Charles Soule", illustrator: "Jesus Saiz", company: "Marvel Comics", protagonist: "Various", cover_illustration: https://comicbookroundup.com/img/covers/s/star-wars-(2020)/1_medium.jpg, release_year: 2020, ongoing: true, synopsis: "In the wake of the events following The Empire Strikes Back, it is a dark time for the heroes of the Rebellion. The Rebel fleet...scattered following a disastrous defeat at the Battle of Hoth. Han Solo...lost to the bounty hunter, Boba Fett, after being frozen in carbonite. And after being lured into a trap on Cloud City and bested in a vicious lightsaber duel against the evil Darth Vader, Luke Skywalker...learned the horrible truth about his past. Vader did not kill Luke's father Anakin--Vader is Luke's father! Now, after narrowly escaping the dark lord's clutches, and wounded and reeling from the revelation, Luke, Princess Leia, Lando Calrissian, the Wookiee Chewbacca and the droids C-3PO and R2-D2 must fight their way back to the Rebel Alliance-for the fate of the entire galaxy is at stake! After so many losses is victory still possible?  But, what Leia, Luke and their ragtag band of freedom fighters do not realize is that they have only traded one Imperial trap for another! Enter the cunning and vengeful Imperial Commander Zahra, at the helm of the Tarkin's Will!")

Comic.create(name: "Black Panther", author: "John Ridley", illustrator: "Juan Cabal", company: "Marvel Comics", protagonist: "Black Panther", cover_illustration: https://comicbookroundup.com/img/covers/b/black-panther-(2021)/1_medium.jpg, release_year: 2021, ongoing: true, synopsis: "Academy Award-winning writer John Ridley and Stormbreaker artist Juann Cabal launch an all-new BLACK PANTHER series with an action-packed espionage story that will upend everything in T’Challa’s life and have ramifications for the entire Marvel Universe! Secrets from T’Challa’s past have come back to haunt him! Fresh from returning from his travels in space, Black Panther receives an unexpected and urgent message from a Wakandan secret agent! Now T’Challa must race the clock not only to save his agent, but also to keep his true agenda under wraps. Because if the truth comes out, it could cost T’Challa everything…")

Comic.create(name: "Captain Marvel", author: "Kelly Thompson", illustrator: "Carmen Nunez Carnero", company: "Marvel Comics", protagonist: "Captain Marvel", cover_illustration: https://comicbookroundup.com/img/covers/c/captain-marvel-(2019)/1_medium.jpg, release_year: 2019, ongoing: true, synopsis: "As Captain Marvel, Carol Danvers has spent months in space protecting Earth from alien threats big and small, but now it's time for Earth's mightiest hero to come home. New York City has never looked so good. But every re-entry comes with the unexpected, and Carol is about to hit a whole lot of unexpected. It's a fresh start and an oversized, star-studded welcome home for a hero who's been punching the glass ceiling since the 1970s - and just in time for the first female-led film from Marvel Studios! The next 50 years of Captain Marvel starts here!")

Comic.create(name: "Wolverine", author: "Ben Percy", illustrator: "Adam Kubert", company: "Marvel Comics", protagonist: "Wolverine", cover_illustration: https://comicbookroundup.com/img/covers/w/wolverine-(2020)/1_medium.jpg, release_year: 2020, ongoing: true, synopsis: "Wolverine has been through a lot. He's been a loner. He's been a killer. He's been a hero. He's been an Avenger. He's been to hell and back. Now, as the nation of Krakoa brings together all Mutantkind, he can finally be... happy? With his family all together and safe, Wolverine has everything he ever wanted... and everything to lose. Writer Benjamin Percy (X-FORCE, WOLVERINE: THE LONG NIGHT) and legendary artist Adam Kubert (X-MEN, AVENGERS) bring the best there is to his new home! PLUS: The return of OMEGA RED!")

Comic.create(name: "Infinity Gauntlet", author: "Jim Starlin", illustrator: "George Perez/Ron Lim", protagonist: "The Avengers", cover_illustration: https://comicbookroundup.com/img/covers/i/infinity-gauntlet-(1991)/1_medium.jpg, release_year: 1991, ongoing: false, synopsis: "For Thanos, the Infinity Gauntlet was the ultimate prize to be coveted above all else. With it came omnipotence. Now it's up to Earth's super heroes to make a desperate attempt to thwart this mad god's insane plunge into galactic self-destruction.")

Comic.create(name: "Civil War", author: "Mark Millar", illustrator: "Steve McNiven", company: "Marvel Comics", protagonist: "Captain America", cover_illustration: https://comicbookroundup.com/img/covers/c/civil-war/1_medium.jpg, release_year: 2005, ongoing: false, synopsis: "A conflict has been brewing in the Marvel Universe for over a year, threatening to pit friend against friend, brother against brother--and all it will take is a single misstep to cost thousands their lives and ignite the fuse! As the war claims its first victims, no one is safe as teams, friendships, and families begin to fall apart. Civil War, a Marvel Comics event in seven parts, stars Spider-Man, the New Avengers, the Fantastic Four, the X-Men and the entirety of the Marvel pantheon! Civil War -- the cross-over that rewrites the rules - begins here in this double-sized first issue!")

Comic.create(name: "Ghost Rider", author: "Ben Percy", illustrator: "Cory Smith", company: "Marvel Comics", protagonist: "Ghost Rider", cover_illustration: https://comicbookroundup.com/img/covers/g/ghost-rider-(2022)/1_medium.jpg, release_year: 2022, ongoing: false, synopsis: "Johnny Blaze has the perfect life: a wife and two kids, a job at an auto repair shop and a small-town community that supports him... But Johnny isn't doing well. He has nightmares of monsters when he sleeps. And he sees bloody visions when he's awake. This life is beginning to feel like a prison. And there's a spirit in him that's begging to break out! Benjamin Percy (WOLVERINE, X-FORCE) and Cory Smith (CONAN THE BARBARIAN, CAPTAIN MARVEL) are going back to basics with the Spirit of Vengeance in this extra-sized first issue!")

Comic.create(name: "Venom", author: "Ram V", illustrator: "Al Ewing", company: "Marvel Comics", protagonist: "Venom", cover_illustration: https://comicbookroundup.com/img/covers/v/venom-(2021)/1_medium.jpg, release_year: 2021, ongoing: true, synopsis: "AN EPIC NEW ERA FOR THE SINISTER SYMBIOTE STARTS HERE! Hot off the heels of VENOM #200 and EXTREME CARNAGE, we’re closing out 2021 with one of the most ambitious books in symbiote history – an all-new VENOM from some of comics’ greatest talents! Marvel mainstay AL EWING, who himself has just ended a character-redefining run on IMMORTAL HULK, is being joined by RAM V, a horror maestro all his own, to craft a mind-bending and gut-wrenching tale of symbiosis the likes of which the Marvel Universe has never seen! AS IF THAT WASN’T ENOUGH, they’ve been joined by industry legend BRYAN HITCH, who is leaving IT ALL ON THE PAGE! We haven’t led you astray yet, have we? So trust us when we tell you that you have NEVER seen a VENOM like this!")

Comic.create(name: "Thor", author: "Donny Cates", illustrator: "Nic Klein", company: "Marvel Comics", protagonist: "Thor", cover_illustration: https://comicbookroundup.com/img/covers/t/thor-(2020)/1_medium.jpg, release_year: 2020, ongoing: true, synopsis: "The prince is now a king. All Asgard lies before Thor, the God of Thunder. And after many months of war, the Ten Realms are finally at peace. But the skies above the Realm Eternal are never clear for long. The Black Winter is coming. And the God of the Storm will be powerless before it.")

Comic.create(name: "Fantastic Four", author: "Dan Slott", illustrator: "Paco Medina", company: "Marvel Comics", protagonist: "Fantastic Four", cover_illustration: https://comicbookroundup.com/img/covers/f/fantastic-four-(2018)/1_medium.jpg, release_year: 2018, ongoing: true, synopsis: "Since the end of SECRET WARS, there's been a gap in the Marvel Universe. A void no other team can fill. And it's time for the world to move on. But can it? A life-changing decision by the Thing! A momentous declaration by the Human Torch! A clarion call-to-arms that summons Doctor Doom! And a signal in the sky that heralds the return of hope to the Marvel Universe! All this, and Alicia Masters adopts kittens! So cute! Plus, the Impossible Man!")

Comic.create(name: "Deadpool Kills The Marvel Universe", author: "Cullen Bunn", illustrator: "Dalibor Talajic", company: "Marvel Comics", protagonist: "Deadpool", cover_illustration: https://pictures.abebooks.com/isbn/9780785164036-us.jpg, release_year: 2012, ongoing: false, synopsis: "What if everthing you thought was funny about Deadpool…was actually just disturbing? What if he decided to kill everyone and everything that makes up the Marvel Universe? What if he actually pulled it off? Would that be FUN for you? The Merc with a Mouth takes a turn for the twisted in a weekly horror comic like no other…")

Comic.create(name: "Rocket Raccoon", author: "Skottie Young", illustrator: "Skottie Young", company: "Marvel Comics", protagonist: "Rocket Raccoon", cover_illustration: https://comicbookroundup.com/img/covers/r/rocket-raccoon/1_medium.jpg, release_year: 2014, ongoing: false, synopsis: "As defenders of the cosmos go, Rocket Raccoon has faced his fair share of galactic battles. He's been a hero to the weak, a champion of good, a protector of the innocent, a heartthrob to the many intergalactic female species and now--a raccoon on the run?! ( I'm sorry, I'm sorry, a formidable-and-expert-Guardian on the run. Rocket is NOT a raccoon, okay?) Rocket's high-flying life of adventure and heroism may soon be a thing of the past when he becomes a wanted man-and the authorities are not the only one on his TAIL! (We'll definitely be overusing that pun!)")





Comic.create(name: "Action Comics", author: "Philip Kennedy Johnson", illustrator: "Riccardo Federici", company: "DC Comics", protagonist: "Superman", cover_illustration: https://comicbookroundup.com/img/covers/a/action-comics-(2016)/957_medium.jpg, release_year: 2016, ongoing: true, synopsis: "Superman returns to Metropolis just in time to meet the city of tomorrows newest protector: Lex Luthor. But its not long before these dueling titans meet someone unexpected the new Clark Kent! DONT MISS: ACTION COMICS returns to its original numbering with this issue!")

Comic.create(name: "Batman", author: "Tom King", illustrator: "Jorge Jimenez", company: "DC Comics", protagonist: "Batman", cover_illustration: https://comicbookroundup.com/comic-books/reviews/dc-comics/batman-(2016), release_year: 2016, ongoing: true, synopsis: "No one has ever stopped the Caped Crusader. Not The Joker. Not Two-Face. Not even the entire Justice League. But how does Batman confront a new hero who wants to save the city from the Dark Knight?")

Comic.create(name: "Batman/Superman: World's Finest", author: "Mark Waid", illustrator: "Dan Mora", company: "DC Comics", protagonist: "Batman/Superman", cover_illustration: https://comicbookroundup.com/img/covers/b/batman--superman-worlds-finest-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "The Dark Knight. The Man of Steel. They are the two finest superheroes that the world has ever known...and they're together again in an epic new series from the legendary talents of Mark Waid and Dan Mora! In the not-too-distant past, Superman's powers are super-charged from a devastating chemical attack by the villain Metallo...and the only ally that the ultra-powerful Man of Tomorrow can turn to in this turbulent hour is Gotham's own dark vengeance: the Batman. A nearly fatal burst of power drives Bruce Wayne to his own extreme measures to help his friend...enlisting none other than the Doom Patrol for aid. It's the world's greatest superheroes from the world's greatest comic book talent in an epic comic book experience that kicks off the next big events in the DCU. Get ready, it's time to soar!")

Comic.create(name: "Black Adam", author: "Christopher Priest", illustrator: "Rafael Sandoval", company: "DC Comics", protagonist: "Black Adam", cover_illustration: https://comicbookroundup.com/img/covers/b/black-adam-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "There is no forgiveness for Black Adam. This is the reality Teth-Adam, immortal man of indomitable will, must face when he discovers he has been infected with an incurable plague destroying his immortality. Haunted by the specter of centuries of dark deeds, Black Adam transfers his powers to a worthy successor who will redeem Adam's legacy and defend their ancestral homeland of Kahndaq, only to subsequently become mystically handcuffed to him when Adam's plague is arrested, giving birth to perhaps the most volatile and dysfunctional super-team in DC history! Powered by stunning art by Rafa Sandoval (Justice League) and breathtaking painted covers by Irvin Rodriguez (Detective Comics), writer Christopher Priest (Deathstroke, Justice League) brings his trademark wit and skill for character deconstruction to an entirely fresh examination of the man you love to hate! Get ready to ride the lightning!")

Comic.create(name: "Catwoman", author: "Joelle Jones", illustrator: "Joelle Jones", company: "DC Comics", protagonist: "Catwoman", cover_illustration: https://comicbookroundup.com/img/covers/c/catwoman-(2018)/1_medium.jpg, release_year: 2018, ongoing: true, synopsis: "The wedding night's barely over, but Catwoman's back on the streets, this time to expose a copycat who's pulling heists around Gotham City. As Selina cracks the whip on her former criminal cohorts, she's attracting unwanted attention from one of Gotham's most dangerous groups. The mob? Nope. Try the GCPD. And as if the Bat-Bride didn't have enough problems, don't miss the debut of an all-new villain determined to make trouble for all nine of Selina's lives. Don't miss the start of an all-new monthly series written and illustrated by Eisner Award-nominee Joëlle Jones!")

Comic.create(name: "Deathstroke Inc.", author: "Joshua Williamson", illustrator: "Howard Porter", company: "DC Comics", protagonist: "Deathstroke", cover_illustration: https://comicbookroundup.com/img/covers/d/deathstroke-inc-(2021)/1_medium.jpg, release_year: 2021, ongoing: true, synopsis: "After suffering too many losses, Slade Wilson decides it’s time for a change. When he’s enlisted to work with an ages-old secret organization called T.R.U.S.T. who want to take down the heavy-hitter villains, he’s all in. They’ll supply him with an all-new team and resources for his new mission into the depths of the weirdest parts of the DCU, including a new partner…Black Canary! Wait what?! Enjoy explosions, kick-ass action, and new outrageous adventures as DC’s meanest S.O.B. gets tangled up in a major mystery building in the shadows of the DCU.")

Comic.create(name: "Detective Comics", author: "Mariko Tamaki", illustrator: "Ivan Reis", company: "DC Comics", protagonist: "Batman", cover_illustration: https://comicbookroundup.com/img/covers/d/detective-comics-(2016)/934_medium.jpg, release_year: 2016, ongoing: true, synopsis: "An unknown predator begins outdoing Batman, taking down dangerous threats with military precision. Its up to the Dark Knight and series costar Batwoman to rally and train the young heroes of Gotham City to end this mysterious threat! WHAT NOW: Batman and Batwoman begin training Spoiler, Red Robin and Cassandra Cain, but is the villainous Clayface ready for redemption?")

Comic.create(name: "Flash", author: "Jeremy Adams", illustrator: "Fernando Pasarin", company: "DC Comics", protagonist: "Flash", cover_illustration: https://comicbookroundup.com/img/covers/f/flash-(2016)/1_medium.jpg, release_year: 2016, ongoing: true, synopsis: "A new storm brews over Central City and disproves the old adage about lightning never, well...you know. Just as Barry begins to feel overwhelmed fighting crime, a new speedster debuts-but just where did this amazing new friend come from?")

Comic.create(name: "Harley Quinn", author: "Stephanie Phillips", illustrator: "Riley Rossmo", company: "DC Comics", protagonist: "Harley Quinn", cover_illustration: https://comicbookroundup.com/img/covers/h/harley-quinn-(2021)/1_medium.jpg, release_year: 2021, ongoing: true, synopsis: "Ahem! You better read this closely, ’cause we’ve got a red-hot relaunch on our hands here-and I should know! Harley Quinn here to let everyone know that I got a brand-new monthly series here with a brand-new status quo. I’m coming back to Gotham City to make up for the sins of my past, and help the city recover from “The Joker War”! But there’s no welcoming committee waiting for me, your favorite Maid of Mischief! And between you and me, some real creeps are working to keep the city broken. We can’t let that happen, can we? Rising-star writer Stephanie Phillips, my new partner in crime, takes me into a bold new era with her partner in artistic crime Riley Rossmo, who I gotta say designed a real nice new costume for me. You’re not gonna wanna miss this one, folks!")

Comic.create(name: "Justice League", author: "Brian Michael Bendis", illustrator: "Jorge Jimenez", company: "DC Comics", protagonist: "Justice League", cover_illustration: https://comicbookroundup.com/img/covers/j/justice-league-(2018)/1_medium.jpg, release_year: 2018, ongoing: true, synopsis: "A brand-new era begins here! Comics legends Scott Snyder and Jim Cheung launch the Justice League into a cosmos-shaking mystery that will draw out their most terrible foes...in ways our heroes couldn't possibly imagine! In this debut issue, Martian Manhunter struggles to protect the team from an incoming threat that will shatter the world as they know it, while a familiar face strikes out on a dark path...")

Comic.create(name: "Monkey Prince", author: "Gene Luen Yang", illustrator: "Bernard Chang", company: "DC Comics", protagonist: "Monkey Prince", cover_illustration: https://comicbookroundup.com/img/covers/m/monkey-prince-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "Introducing the newest hero in the DCU, the great sage, equal to the heavens, better than his predecessor the legendary Monkey King, even better than the Justice League-and definitely the Teen Titans-(actually, all the heroes combined), everyone put your hands together for…the Monkey Prince! Marcus Sun moves around a lot because his adoptive parents are freelance henchpeople, so this month he finds himself as the new kid at Gotham City High School, where a mysterious man with pig features asks Marcus to walk through a water curtain to reveal himself as who Marcus really is…someone who has adventured through The Journey to the West, can transform into 72 different formations, can clone himself using his hairs, and is called…the Monkey Prince!")

Comic.create(name: "Nightwing", author: "Tim Seely", illustrator: "Javi Fernandez", company: "DC Comics", protagonist: "Nightwing", cover_illustration: https://comicbookroundup.com/img/covers/n/nightwing-(2016)/1_medium.jpg, release_year: 2016, ongoing: true, synopsis: "Batman taught Nightwing everything he knows-but what if everything he taught him is wrong? When Dick is stuck with a new mentor who challenges everything Batman taught him, Nightwing has to shatter his concept of justice in order to fight for what he knows is right.")

Comic.create(name: "Poison Ivy", author: "G. Willow Wilson", illustrator: "Marcio Takara", company: "DC Comics", protagonist: "Poison Ivy", cover_illustration: https://comicbookroundup.com/img/covers/p/poison-ivy-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "Pamela Isley has been a lot of things in her life. A living god, a super-villain, an activist, a scientist, and dead. In a new body that she didn't ask for and with a renewed sense of purpose, Ivy leaves Gotham and sets out to complete her greatest work-a gift to the world that will heal the damage dealt to it...by ending humanity.")

Comic.create(name: "Robin", author: "Joshua Williamson", illustrator: "Gleb Melnikov", company: "DC Comics", protagonist: "Robin", cover_illustration: https://comicbookroundup.com/img/covers/r/robin-(2021)/1_medium.jpg, release_year: 2021, ongoing: true, synopsis: "After learning of the deadly League of Lazarus tournament, Damian Wayne has a new mission: winning the tournament and prove he is the greatest fighter in the DC Universe! But first he must find the secret island where it’s all going down! This brand-new solo Robin series will force Damian Wayne to find his own path away from both sides of his family! New mysteries! New supporting cast! First appearances of new characters! And lots of fights!")

Comic.create(name: "Rogues", author: "Joshua Williamson", illustrator: "Leomacs", company: "DC Comics", protagonist: "The Rogues", cover_illustration: https://comicbookroundup.com/img/covers/r/rogues-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "Ten years ago, the Rogues disbanded and went their separate ways. But time hasn't been kind to the former blue-collar super-criminals. Caught in an endless cycle of prison, rehab, dead-end jobs, broken relationships, probation, and endless restitution fees, the Rogues are sick of paying for their crimes. Luckily, Captain Cold has a plan. One last job that will leave them all richer than their wildest dreams and free from their past...if they can survive. This is the Rogues as you've never seen them before, reimagined by the incredible talents of master storytellers Leomacs (Basketful of Heads) and Joshua Williamson (Batman, The Flash, Infinite Frontier). DC Black Label presents Rogues, a neo-noir heist that will make your blood run cold.")

Comic.create(name: "Suicide Squad: Blaze", author: "Simon Spurrier", illustrator: "Aaron Campbell", company: "DC Comics", protagonist: "Suicide Squad", cover_illustration: https://comicbookroundup.com/img/covers/s/suicide-squad-blaze-(2022)/1_medium.jpg, release_year: 2022, ongoing: true, synopsis: "The attacks begin without warning. Brutal, sudden…cannibalistic. A metahuman with all the power of Superman but none of his humanity. An unstoppable being ruled only by hunger and instinct, striking at random across the world. To stop this threat, Harley Quinn, Peacemaker, Captain Boomerang, and King Shark have been assigned to corral, nursemaid, and if necessary execute five deadly new recruits: the expendable products of a secret government procedure called BLAZE. They’re ordinary prisoners, endowed with incredible power…and the certain knowledge that it’ll burn through them like wildfire. They have six months to live, maximum. If you’re staring down life in prison, maybe that’s a good deal-especially if you’re Michael Van Zandt, desperate to reunite with the mad lover who forsook you after your Bonnie-and-Clyde crime spree. But that power? It’s surprisingly transferable. As each member of the Squad dies…the others get stronger. What would a hardened criminal do with that knowledge? Worse yet: What would a desperate, lovesick idiot do with it? One thing’s certain: this time the Suicide Squad’s bitten off more than it can chew.")

Comic.create(name: "The Swamp Thing", author: "Ram V", illustrator: "Mike Perkins", company: "DC Comics", protagonist: "Swamp Thing", cover_illustration: https://comicbookroundup.com/img/covers/s/swamp-thing-(2021)/1_medium.jpg, release_year: 2021, ongoing: true, synopsis: "Swamp Thing returns in a new 10-issue series that stars Levi Kamei as the next Guardian of the Green. Unable to control his transformation into the monstrous Swamp Thing, Levi is thrust into the harsh, unforgiving mystery of grisly murders committed by a supernatural desert legend. Levi must revisit past events in his homeland of India and face the deadly reality of a ravenous new villain in order to comprehend what he is truly, and horrifyingly, becoming. A new era of global action and horror blossoms here, and Swamp Thing will be at the root of it!")

Comic.create(name: "Batman: The Dark Knight Returns", author: "Frank Miller", illustrator: "Klaus Janson", company: "DC Comics", protagonist: "Batman", cover_illustration: https://comicbookroundup.com/img/covers/b/batman-the-dark-knight-returns/1_medium.jpg, release_year: 1986, ongoing: false, synopsis: "This masterpiece of comics storytelling brings to life a dark world...and an even darker man. Frank Miller completely reinvents the legend of Batman in his saga of a near-future Gotham City gone to rot, ten years after the Dark Knight's retirement.")

Comic.create(name: "All-Star Superman", author: "Grant Morrison", illustrator: "Frank Quitely", company: "DC Comics", protagonist: "Superman", cover_illustration: https://comicbookroundup.com/img/covers/a/all-star-superman/1_medium.jpg, release_year: 2005, ongoing: false, synopsis: "DC launches the newest addition to its All Star line of comics — where the industry's top creative talents refine the iconic focus of the world's greatest super-heroes. Writer Grant Morrison (JLA, SEVEN SOLDIERS) and artist Frank Quitely (THE AUTHORITY, New X-Men) — the acclaimed team behind JLA: EARTH 2 — are at it once again, this time to strip down the Man of Steel to his timeless, essential elements. The series kicks off with a 12-issue story arc touching on all the classic aspects of the Superman mythology, starting with a daring rescue of a doomed group of helionauts on the surface of the sun. The massive amounts of solar radiation affect Superman in a way no one could possibly anticipate — except Lex Luthor!")

Comic.create(name: "Watchmen", author: "Alan Moore", illustrator: "Dave Gibbons", company: "DC Comics", protagonist: "The Watchmen", cover_illustration: https://comicbookroundup.com/img/covers/w/watchmen/1_medium.jpg, release_year: 1985, ongoing: false, synopsis: "Featuring the first appearance of Rorschach, Ozymandias, Dr. Manhattan, Silk Spectre, Nite Owl, and the Comedian! When the Comedian dies, a series of events are set into motion that bring the world ever closer to a deadly threat no one saw coming.")

puts "Seeding done :)"